version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/tuxgo
    binary: tuxgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Osmait/tuxgo/internal/cli.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Breaking Changes
      regexp: '^.*?feat(\(.+\))?!:.*$'
      order: 0
    - title: Features
      regexp: '^.*?feat(\(.+\))?:.*$'
      order: 1
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?:.*$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\(.+\))?:.*$'
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "^test:"

release:
  github:
    owner: Osmait
    name: tuxgo
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
